name: React Example AWS S3

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [15.x]

    steps:
      - uses: actions/checkout@v1
      # - run: yarn
      # - run: yarn test
      - name: print vars
        run: echo "REACT_APP_ENDPOINT=$REACT_APP_ENDPOINT"
      # - name: Create .env
      #   run: |
      #     echo "REACT_APP_ENDPOINT=$REACT_APP_ENDPOINT" >> .env
      # - name: yarn build
      #   run: yarn build # run: REACT_APP_ENDPOINT=$REACT_APP_ENDPOINT yarn build
        env:
          REACT_APP_ENDPOINT: ${{ vars.REACT_APP_ENDPOINT }}
      # - uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "us-west-1" # optional: defaults to us-east-1
      #     SOURCE_DIR: "build" # optional: defaults to entire repository
