name: React Example

on:
  push:
    branches:
      - "main"

env:
  REACT_APP_ENDPOINT: ${{ vars.REACT_APP_ENDPOINT }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn test
      - run: REACT_APP_ENDPOINT=$REACT_APP_ENDPOINT yarn build
      # - name: Print vars
      #   run: |
      #     echo "REACT_APP_ENDPOINT $REACT_APP_ENDPOINT"
      #     echo "REACT_APP_ENDPOINT ${{ vars.REACT_APP_ENDPOINT }}"
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-1" # optional: defaults to us-east-1
          SOURCE_DIR: "build" # optional: defaults to entire repository
